version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=${APP_NAME}
      - APP_VERSION=${APP_VERSION}
      - APP_PORT=${APP_PORT}
      - ENV_NAME=${ENV_NAME}
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - LOGGING=${LOGGING}
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      - AUTH_TOKEN_EXPIRY=${AUTH_TOKEN_EXPIRY}
      - DEFAULT_PAGINATION_LIMIT=${DEFAULT_PAGINATION_LIMIT}
      - DEFAULT_SEARCH_MIN_CHARACTERS=${DEFAULT_SEARCH_MIN_CHARACTERS}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
